"use client";

// Funny Commercial v2 — location library helpers.
//
// Locations are reusable 9:16 backdrops (apartment exteriors, kitchens,
// hallways, etc.) generated by Nano Banana 2 from a free-text prompt.
// They're optional starter references for shot composition — Nano can
// then edit either an actor (by face reference) or an absurd subject
// onto the location.

import { getSlice, setSlice } from "./libraryStore";
import type { FcLocation } from "./types";

export function listFcLocations(): FcLocation[] {
  return getSlice("fcLocations").slice().sort((a, b) => b.savedAt - a.savedAt);
}

export function getFcLocation(id: string): FcLocation | undefined {
  return getSlice("fcLocations").find((l) => l.id === id);
}

export function addFcLocation(input: Omit<FcLocation, "id" | "savedAt">): FcLocation {
  const all = getSlice("fcLocations");
  const existing = all.find((l) => l.imageUrl === input.imageUrl);
  if (existing) return existing;
  const entry: FcLocation = {
    ...input,
    id: `fc-loc-${Date.now()}-${Math.floor(Math.random() * 1e6)}`,
    savedAt: Date.now(),
  };
  setSlice("fcLocations", [...all, entry]);
  return entry;
}

export function removeFcLocation(id: string): FcLocation | undefined {
  const all = getSlice("fcLocations");
  const found = all.find((l) => l.id === id);
  if (!found) return undefined;
  setSlice("fcLocations", all.filter((l) => l.id !== id));
  return found;
}

export function subscribeFcLocations(cb: () => void): () => void {
  if (typeof window === "undefined") return () => undefined;
  const handler = () => cb();
  window.addEventListener("fc-locations-changed", handler);
  return () => window.removeEventListener("fc-locations-changed", handler);
}
