// React templates for the three hand-built graphic post types. Rendered
// to PNG by next/og's ImageResponse (Satori + resvg under the hood).
// Layouts copy the JSX spec from static Designs/design_handoff_social_templates
// — exact pixel values, font choices, and content structure preserved.
//
// Light theme is the only one shipped in v1. Inverse / Halftone / Grid /
// Editorial are planned follow-ups; halftone + grid in particular need
// fallbacks because Satori doesn't support background-clip: text.

import React from "react";
import type {
  AiPosterGraphicData,
  DykGraphicData,
  GraphicData,
  PromoGraphicData,
  StatGraphicData,
} from "./types";
import type {
  PosterPlacement,
  PosterRegion,
  PosterScrim,
} from "./aiPosterPlacement";

export type LogoVariant = "black" | "white";

// Default kicker if a promo card doesn't supply its own. The headline
// + subline are now per-card catchphrase copy generated by Claude;
// we keep the kicker generic because the CTA-pivot question reads
// fine across most catchphrases.
export const DEFAULT_PROMO_KICKER = "Ready to find your agent?";


// ── Shared subcomponents ────────────────────────────────────────────

// Logo — base64 data URL passed in by the route (Satori can't reliably
// reach the host's own public URL during a function invocation).
// Native asset ratio is 1536:545 (~2.82); the design spec uses
// height = size * 2.4 — Satori needs both width AND height set
// explicitly on <img> or it silently drops the element.
const LOGO_RATIO = 1536 / 545;
function Wordmark({ src, size = 28 }: { src: string; size?: number }) {
  const height = size * 2.4;
  const width = Math.round(height * LOGO_RATIO);
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img src={src} alt="Agent Match" width={width} height={height} />
  );
}

// Pill-shaped CTA button used at the bottom of every template. Black
// bg / white text on light themes, inverted on dark.
function CTAButton({ label, inverse = false }: { label: string; inverse?: boolean }) {
  const bg = inverse ? "#fff" : "#000";
  const fg = inverse ? "#000" : "#fff";
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 10,
        background: bg,
        color: fg,
        padding: "18px 28px",
        borderRadius: 999,
        fontFamily: "Geist, Inter, sans-serif",
        fontWeight: 600,
        fontSize: 22,
        letterSpacing: "-0.01em",
        lineHeight: 1,
      }}
    >
      <span>{label}</span>
      <svg width={22} height={22} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M5 12h14M13 5l7 7-7 7"
          stroke={fg}
          strokeWidth="2.4"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </div>
  );
}

// ── Stat Light ──────────────────────────────────────────────────────

// Auto-shrink the giant stat number when the value runs long. Tuned for
// Geist-ExtraBold at 920px content width — anything over ~3 characters
// starts to crowd the gutters at the design's 380px target.
function statNumberFontSize(text: string): number {
  const len = text.length;
  if (len <= 3) return 380;
  if (len === 4) return 300;
  if (len === 5) return 240;
  return 200;
}

// Star adornment rendered as inline SVG. The bundled Geist subset
// doesn't include the U+2605 glyph, so a literal ★ character renders
// as tofu — we paint it ourselves at the same visual weight as the
// number so "4.8★" reads correctly.
function StarAdornment({ size, color = "#000" }: { size: number; color?: string }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M12 2l2.94 6.42L22 9.27l-5 4.87L18.18 21 12 17.77 5.82 21 7 14.14l-5-4.87 7.06-.85L12 2z" />
    </svg>
  );
}

export function StatPostLight({
  fields,
  logoBlackUrl,
}: {
  fields: StatGraphicData;
  logoBlackUrl: string;
}) {
  const numberFontSize = statNumberFontSize(fields.number);
  // Star unit gets rendered as SVG; everything else stays as text at a
  // proportionally smaller fontSize than the number so the unit reads
  // as a suffix rather than a peer.
  const unitText = fields.unit?.trim() ?? "";
  const isStarUnit = unitText === "★" || unitText.toLowerCase() === "stars";
  const unitFontSize = Math.round(numberFontSize * 0.5);
  const headerLabel = `BY THE NUMBERS / ${fields.index ?? "01"}`;
  return (
    <div
      style={{
        width: 1080,
        height: 1350,
        background: "#fff",
        color: "#000",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: 80,
        fontFamily: "Geist, Inter, sans-serif",
      }}
    >
      {/* Header row */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Wordmark src={logoBlackUrl} size={28} />
        <div
          style={{
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 18,
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "#999",
          }}
        >
          {headerLabel}
        </div>
      </div>

      {/* Body */}
      <div style={{ display: "flex", flexDirection: "column" }}>
        <div
          style={{
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 20,
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "#000",
            marginBottom: 32,
            display: "flex",
            alignItems: "center",
            gap: 16,
          }}
        >
          <div style={{ width: 40, height: 2, background: "#000" }} />
          {"The Stat"}
        </div>
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 800,
            fontSize: numberFontSize,
            letterSpacing: "-0.06em",
            lineHeight: 0.85,
            color: "#000",
            display: "flex",
            alignItems: "flex-start",
          }}
        >
          <span>{fields.number}</span>
          {isStarUnit ? (
            <div style={{ display: "flex", marginLeft: 8, marginTop: numberFontSize * 0.05 }}>
              <StarAdornment size={Math.round(numberFontSize * 0.55)} />
            </div>
          ) : unitText ? (
            <span style={{ fontSize: unitFontSize }}>{unitText}</span>
          ) : null}
        </div>
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 500,
            fontSize: 52,
            letterSpacing: "-0.025em",
            lineHeight: 1.1,
            marginTop: 48,
            maxWidth: 880,
          }}
        >
          {fields.statement}
        </div>
        <div
          style={{
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 18,
            color: "#999",
            marginTop: 32,
            letterSpacing: "0.04em",
          }}
        >
          {fields.source}
        </div>
      </div>

      {/* Footer */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
        <CTAButton label="Find Your Agent" />
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 16,
            color: "#999",
            textAlign: "right",
            lineHeight: 1.5,
          }}
        >
          <span>agentxmatch.com</span>
        </div>
      </div>
    </div>
  );
}

// ── DYK Light ───────────────────────────────────────────────────────

export function DykPostLight({
  fields,
  logoBlackUrl,
}: {
  fields: DykGraphicData;
  logoBlackUrl: string;
}) {
  return (
    <div
      style={{
        width: 1080,
        height: 1350,
        background: "#fff",
        color: "#000",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: 80,
        fontFamily: "Geist, Inter, sans-serif",
      }}
    >
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Wordmark src={logoBlackUrl} size={28} />
        <div
          style={{
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 18,
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "#999",
          }}
        >
          {`FACT / ${fields.index}`}
        </div>
      </div>

      {/* Body */}
      <div style={{ display: "flex", flexDirection: "column" }}>
        {/* Eyebrow row */}
        <div style={{ display: "flex", alignItems: "center", gap: 20, marginBottom: 32 }}>
          <div
            style={{
              width: 56,
              height: 56,
              borderRadius: 999,
              background: "#000",
              color: "#fff",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontFamily: "Geist, Inter, sans-serif",
              fontWeight: 700,
              fontSize: 36,
              lineHeight: 1,
            }}
          >
            ?
          </div>
          <div
            style={{
              fontFamily: "Geist, Inter, sans-serif",
              fontWeight: 600,
              fontSize: 36,
              letterSpacing: "-0.02em",
              lineHeight: 1,
            }}
          >
            Did you know?
          </div>
        </div>

        {/* Fact */}
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 700,
            fontSize: 84,
            letterSpacing: "-0.035em",
            lineHeight: 1.0,
          }}
        >
          {fields.fact}
        </div>

        {/* Rule */}
        <div style={{ width: 80, height: 3, background: "#000", marginTop: 48, marginBottom: 32 }} />

        {/* Body */}
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 400,
            fontSize: 32,
            letterSpacing: "-0.01em",
            lineHeight: 1.4,
            color: "#444",
            maxWidth: 880,
          }}
        >
          {fields.body}
        </div>
      </div>

      {/* Footer */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
        <CTAButton label="Get Started" />
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 16,
            color: "#999",
            textAlign: "right",
            lineHeight: 1.5,
          }}
        >
          <span>agentxmatch.com</span>
        </div>
      </div>
    </div>
  );
}

// ── Promo Light ─────────────────────────────────────────────────────

// Promo headline auto-shrinks based on character length. Catchphrases
// are unpredictable in length — a 6-word hook fits beautifully at 124px,
// a 14-word one needs to drop to ~88px to avoid overflowing the card.
function promoHeadlineFontSize(text: string): number {
  const len = text.length;
  if (len <= 28) return 124;
  if (len <= 44) return 108;
  if (len <= 64) return 92;
  return 76;
}

function promoSublineFontSize(text: string): number {
  const len = text.length;
  if (len <= 60) return 56;
  if (len <= 100) return 46;
  return 38;
}

export function PromoPostLight({
  fields,
  logoBlackUrl,
}: {
  fields: PromoGraphicData;
  logoBlackUrl: string;
}) {
  const headlineFontSize = promoHeadlineFontSize(fields.headline);
  const sublineFontSize = promoSublineFontSize(fields.subline);
  const kicker = fields.kicker?.trim() || DEFAULT_PROMO_KICKER;
  return (
    <div
      style={{
        width: 1080,
        height: 1350,
        background: "#fff",
        color: "#000",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: 80,
        fontFamily: "Geist, Inter, sans-serif",
      }}
    >
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Wordmark src={logoBlackUrl} size={28} />
        <div
          style={{
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 18,
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "#999",
          }}
        >
          {"Find your match"}
        </div>
      </div>

      {/* Body */}
      <div style={{ display: "flex", flexDirection: "column" }}>
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 800,
            fontSize: headlineFontSize,
            letterSpacing: "-0.045em",
            lineHeight: 0.95,
            color: "#000",
            maxWidth: 920,
          }}
        >
          {fields.headline}
        </div>
        <div style={{ width: 80, height: 3, background: "#000", marginTop: 44, marginBottom: 44 }} />
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 500,
            fontSize: sublineFontSize,
            letterSpacing: "-0.025em",
            lineHeight: 1.15,
            color: "#444",
            maxWidth: 920,
          }}
        >
          {fields.subline}
        </div>
      </div>

      {/* Footer */}
      <div style={{ display: "flex", flexDirection: "column" }}>
        <div
          style={{
            fontFamily: "Geist, Inter, sans-serif",
            fontWeight: 600,
            fontSize: 36,
            letterSpacing: "-0.02em",
            color: "#000",
            marginBottom: 24,
          }}
        >
          {kicker}
        </div>
        <CTAButton label="Get Started" />
        <div
          style={{
            fontFamily: "JetBrainsMono, monospace",
            fontSize: 16,
            color: "#999",
            textAlign: "right",
            lineHeight: 1.5,
            marginTop: 16,
          }}
        >
          {"agentxmatch.com"}
        </div>
      </div>
    </div>
  );
}

// ── AI Poster Composite (text over Nano-generated bare image) ──────

// Auto-shrink the headline based on character length. Tuned for Geist
// Black on a 1080-wide canvas with comfortable margins. Subline scales
// proportionally so the visual weight ratio stays consistent.
function aiHeadlineFontSize(text: string): number {
  const len = text.trim().length;
  if (len <= 12) return 156;
  if (len <= 22) return 124;
  if (len <= 32) return 100;
  return 84;
}
function aiSublineFontSize(headlinePx: number): number {
  // Subline is ~36-42% of headline size — strong hierarchy without
  // crowding the type stack.
  return Math.max(30, Math.round(headlinePx * 0.38));
}

// Map a placement region to flexbox alignment + padding for the
// text block. The full canvas is 1080x1350; we leave a generous
// 80px gutter on every side and let the chosen region pin the text
// block accordingly.
function blockLayoutForRegion(region: PosterRegion): React.CSSProperties {
  const base: React.CSSProperties = {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    padding: "80px",
    width: "100%",
    height: "100%",
    boxSizing: "border-box",
  };
  switch (region) {
    case "top":
      return { ...base, justifyContent: "flex-start", alignItems: "flex-start" };
    case "bottom":
      return { ...base, justifyContent: "flex-end", alignItems: "flex-start" };
    case "left":
      return { ...base, justifyContent: "center", alignItems: "flex-start" };
    case "right":
      // Right-rail layouts read better with right-anchored text.
      return { ...base, justifyContent: "center", alignItems: "flex-end" };
    case "center":
      return { ...base, justifyContent: "center", alignItems: "center" };
  }
}

// Map a scrim choice to a CSS gradient backgroundImage. Each fade is
// strong enough to lift white text off a busy region but soft enough
// to keep the image readable as the hero. The vignette uses a radial
// edge fade (Satori does support radial-gradient).
function scrimStyle(scrim: PosterScrim): React.CSSProperties | null {
  switch (scrim) {
    case "none":
      return null;
    case "bottom-fade":
      return {
        backgroundImage:
          "linear-gradient(to top, rgba(0,0,0,0.78) 0%, rgba(0,0,0,0.55) 28%, rgba(0,0,0,0.0) 60%)",
      };
    case "top-fade":
      return {
        backgroundImage:
          "linear-gradient(to bottom, rgba(0,0,0,0.78) 0%, rgba(0,0,0,0.55) 28%, rgba(0,0,0,0.0) 60%)",
      };
    case "left-fade":
      return {
        backgroundImage:
          "linear-gradient(to right, rgba(0,0,0,0.78) 0%, rgba(0,0,0,0.55) 30%, rgba(0,0,0,0.0) 65%)",
      };
    case "right-fade":
      return {
        backgroundImage:
          "linear-gradient(to left, rgba(0,0,0,0.78) 0%, rgba(0,0,0,0.55) 30%, rgba(0,0,0,0.0) 65%)",
      };
    case "vignette":
      return {
        backgroundImage:
          "radial-gradient(ellipse at center, rgba(0,0,0,0.0) 35%, rgba(0,0,0,0.55) 75%, rgba(0,0,0,0.78) 100%)",
      };
  }
}

// The wordmark sits in the corner OPPOSITE the text, so it doesn't
// crowd the headline. For center-text layouts we tuck it bottom-right
// since the vignette protects it.
function wordmarkCornerForRegion(region: PosterRegion): {
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
} {
  switch (region) {
    case "top":    return { bottom: 64, left: 64 };
    case "bottom": return { top: 64, right: 64 };
    case "left":   return { top: 64, right: 64 };
    case "right":  return { top: 64, left: 64 };
    case "center": return { bottom: 64, right: 64 };
  }
}

// Localized "halo" backdrop behind the text block. This is the safety
// net that guarantees legibility even when Vision picks a region that
// turns out to overlap with image content (e.g., the chameleon's head
// reaching into a TOP region). Unlike the full-edge scrim, the halo
// is bounded to roughly the text's bounding box and feathers softly
// to transparent at the edges via a radial gradient — the image
// stays visible everywhere except directly behind the type, so the
// effect reads as intentional editorial design rather than a fix.
//
// Geometry returned in pixel units against the 1080x1350 canvas. The
// box is generously oversized vs. the actual text rect so the
// feathered radial gradient has room to fall off without clipping
// the readable zone.
interface HaloBox {
  top: number;
  left: number;
  width: number;
  height: number;
}
function haloBoxForRegion(region: PosterRegion): HaloBox {
  // Canvas is 1080x1350, padding is 80px on all sides for the text
  // block. We oversize the halo box ~120px in each direction past the
  // text padding so the gradient feathers into clean image area.
  switch (region) {
    case "top":
      return { top: 0, left: 0, width: 1080, height: 540 };
    case "bottom":
      return { top: 810, left: 0, width: 1080, height: 540 };
    case "left":
      return { top: 0, left: 0, width: 720, height: 1350 };
    case "right":
      return { top: 0, left: 360, width: 720, height: 1350 };
    case "center":
      return { top: 270, left: 90, width: 900, height: 810 };
  }
}

// Soft radial gradient bounded to the halo box. Strong opacity at the
// center, fades to fully transparent before the box edges so the
// image isn't visibly cropped — the falloff IS the feather.
//
// `tone` toggles dark vs light halo: dark behind white text, light
// behind black text. Opacity tuned by feel — strong enough to lift
// type off a busy photo, soft enough to feel intentional.
function haloBackground(tone: "dark" | "light"): string {
  if (tone === "dark") {
    return [
      "radial-gradient(ellipse 75% 75% at center,",
      "rgba(0,0,0,0.62) 0%,",
      "rgba(0,0,0,0.50) 35%,",
      "rgba(0,0,0,0.28) 60%,",
      "rgba(0,0,0,0.0) 88%)",
    ].join(" ");
  }
  return [
    "radial-gradient(ellipse 75% 75% at center,",
    "rgba(255,255,255,0.72) 0%,",
    "rgba(255,255,255,0.55) 35%,",
    "rgba(255,255,255,0.30) 60%,",
    "rgba(255,255,255,0.0) 88%)",
  ].join(" ");
}

export function AiPosterCompositeLight({
  fields,
  imageDataUrl,
  placement,
  logoBlackUrl,
  logoWhiteUrl,
}: {
  fields: AiPosterGraphicData;
  imageDataUrl: string;       // base64 data URL of the bare AI image
  placement: PosterPlacement;
  logoBlackUrl: string;
  logoWhiteUrl: string;
}) {
  const headlinePx = aiHeadlineFontSize(fields.headline);
  const sublinePx = aiSublineFontSize(headlinePx);
  const layoutStyle = blockLayoutForRegion(placement.region);
  const scrim = scrimStyle(placement.scrim);
  const corner = wordmarkCornerForRegion(placement.region);
  const isWhiteText = placement.textColor === "white";
  const textColor = isWhiteText ? "#fff" : "#000";
  const sublineColor = isWhiteText ? "rgba(255,255,255,0.88)" : "rgba(0,0,0,0.78)";
  // White wordmark on dark scrims; black wordmark otherwise.
  const wordmarkSrc = isWhiteText ? logoWhiteUrl : logoBlackUrl;
  // A subtle text shadow buys legibility on edges of the scrim where
  // contrast is borderline. Spread conditionally — Satori chokes if a
  // CSS property arrives as `undefined` (it tries to .toString() it).
  // For black-on-light combos we skip the shadow entirely; dark glyphs
  // on light pixels rarely need it and a shadow can muddy the type.
  const headlineShadowStyle: React.CSSProperties = isWhiteText
    ? { textShadow: "0 2px 6px rgba(0,0,0,0.55), 0 1px 2px rgba(0,0,0,0.5)" }
    : {};

  // Localized halo backdrop bounded to the chosen region. This is the
  // safety net for cases where Vision picked a region that turns out
  // to overlap with image content. Dark halo behind white text, light
  // halo behind black text. Sits between the image and the text block.
  const halo = haloBoxForRegion(placement.region);
  const haloBg = haloBackground(isWhiteText ? "dark" : "light");

  // Text block is constrained to 880px so headlines wrap predictably
  // even when the placement is left/right rail.
  const textBlockMaxWidth = 880;

  return (
    <div
      style={{
        position: "relative",
        width: 1080,
        height: 1350,
        display: "flex",
        backgroundColor: "#000",
        backgroundImage: `url(${imageDataUrl})`,
        backgroundSize: "1080px 1350px",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        fontFamily: "Geist, Inter, sans-serif",
      }}
    >
      {/* Scrim layer (optional) — full-edge gradient across the canvas */}
      {scrim ? (
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: 1080,
            height: 1350,
            display: "flex",
            ...scrim,
          }}
        />
      ) : null}

      {/* Localized halo — bounded to the text region with feathered edges */}
      <div
        style={{
          position: "absolute",
          top: halo.top,
          left: halo.left,
          width: halo.width,
          height: halo.height,
          display: "flex",
          backgroundImage: haloBg,
        }}
      />

      {/* Text block */}
      <div style={layoutStyle}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            maxWidth: textBlockMaxWidth,
            textAlign: placement.region === "right" ? "right" : "left",
          }}
        >
          <div
            style={{
              fontFamily: "Geist, Inter, sans-serif",
              fontWeight: 900,
              fontSize: headlinePx,
              letterSpacing: "-0.045em",
              lineHeight: 0.95,
              color: textColor,
              ...headlineShadowStyle,
            }}
          >
            {fields.headline}
          </div>
          {fields.subline ? (
            <div
              style={{
                fontFamily: "Geist, Inter, sans-serif",
                fontWeight: 500,
                fontSize: sublinePx,
                letterSpacing: "-0.02em",
                lineHeight: 1.2,
                color: sublineColor,
                marginTop: 28,
                ...headlineShadowStyle,
              }}
            >
              {fields.subline}
            </div>
          ) : null}
        </div>
      </div>

      {/* Wordmark in the corner opposite the text */}
      <div
        style={{
          position: "absolute",
          display: "flex",
          ...corner,
        }}
      >
        <Wordmark src={wordmarkSrc} size={26} />
      </div>
    </div>
  );
}

// ── Public dispatcher ───────────────────────────────────────────────

export function renderTemplate(args: {
  graphic: GraphicData;
  logoBlackUrl: string;
  logoWhiteUrl: string;
  // Only required for ai_poster — the bare image as a base64 data URL
  // and the Vision-picked text placement. Other templates ignore these.
  aiPosterImage?: string;
  aiPosterPlacement?: PosterPlacement;
}): React.ReactElement {
  const { graphic, logoBlackUrl, logoWhiteUrl, aiPosterImage, aiPosterPlacement } = args;
  switch (graphic.template) {
    case "stat":
      return <StatPostLight fields={graphic} logoBlackUrl={logoBlackUrl} />;
    case "did_you_know":
      return <DykPostLight fields={graphic} logoBlackUrl={logoBlackUrl} />;
    case "promo":
      return <PromoPostLight fields={graphic} logoBlackUrl={logoBlackUrl} />;
    case "ai_poster":
      if (!aiPosterImage || !aiPosterPlacement) {
        throw new Error(
          "ai_poster requires aiPosterImage (data URL) + aiPosterPlacement",
        );
      }
      return (
        <AiPosterCompositeLight
          fields={graphic}
          imageDataUrl={aiPosterImage}
          placement={aiPosterPlacement}
          logoBlackUrl={logoBlackUrl}
          logoWhiteUrl={logoWhiteUrl}
        />
      );
  }
}
