import { NextResponse } from "next/server";
import JSZip from "jszip";
import { buildFcpxml, type FcpxmlClipSpec } from "@/lib/fcpxml";

export const runtime = "nodejs";
export const maxDuration = 300;

// POST /api/story/export-zip
//
// Body:
//   {
//     sequenceName: string,
//     timeline: Array<{
//       slotIndex: number,
//       clipUrl: string,
//       durationS: number,
//     }>
//   }
//
// Response: an `application/zip` blob containing:
//   - timeline.xml          (Final Cut Pro 7 XML, Premiere-importable)
//   - clips/<slotIdx>-<basename>.mp4
//
// The XML uses relative paths (`file://./clips/...`) so the zip is
// portable — extract anywhere and Premiere resolves siblings. No
// narration, no overlay text — Story Builder v1 sequences raw clips.

interface Body {
  sequenceName: string;
  timeline: Array<{
    slotIndex: number;
    clipUrl: string;
    durationS: number;
  }>;
}

function safeBaseName(url: string): string {
  try {
    const u = new URL(url);
    const last = u.pathname.split("/").pop() ?? "clip";
    return last.replace(/[^a-z0-9._-]+/gi, "-").slice(0, 60) || "clip";
  } catch {
    return "clip";
  }
}

async function fetchBytes(url: string, label: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${label} fetch failed: ${res.status}`);
  }
  return new Uint8Array(await res.arrayBuffer());
}

export async function POST(req: Request) {
  try {
    const body = (await req.json()) as Body;
    if (!body.sequenceName?.trim()) {
      return NextResponse.json({ error: "sequenceName is required" }, { status: 400 });
    }
    if (!Array.isArray(body.timeline) || body.timeline.length === 0) {
      return NextResponse.json({ error: "timeline (non-empty) is required" }, { status: 400 });
    }

    const zip = new JSZip();
    const clipsFolder = zip.folder("clips")!;

    const clipSpecs: FcpxmlClipSpec[] = await Promise.all(
      body.timeline.map(async (slot) => {
        const baseName = safeBaseName(slot.clipUrl);
        const clipFileName = `${slot.slotIndex}-${baseName.endsWith(".mp4") ? baseName : `${baseName}.mp4`}`;
        const clipBytes = await fetchBytes(slot.clipUrl, `clip ${slot.slotIndex}`);
        clipsFolder.file(clipFileName, clipBytes);
        return {
          slotIndex: slot.slotIndex,
          clipFileName,
          durationS: slot.durationS,
        };
      }),
    );

    const xml = buildFcpxml({
      sequenceName: body.sequenceName,
      clips: clipSpecs,
    });
    zip.file("timeline.xml", xml);

    zip.file(
      "README.txt",
      [
        `${body.sequenceName} — Story Builder export`,
        "",
        "Open `timeline.xml` in Premiere Pro CC (File → Import).",
        "It loads as a 9:16 sequence with V1 clip track + A1 clip audio.",
        "All clip references are relative — extract this zip anywhere and the paths resolve.",
        "",
        "Generated by Content Studio.",
      ].join("\n"),
    );

    const out = await zip.generateAsync({ type: "nodebuffer" });
    return new Response(out as unknown as BodyInit, {
      status: 200,
      headers: {
        "content-type": "application/zip",
        "content-disposition": `attachment; filename="story-${Date.now()}.zip"`,
        "cache-control": "no-store",
      },
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : "unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
